// crates/omega-rpc/src/flashloan_liq.rs
//
// C7 — Flash-loan integration: provider registry / address resolution /
// snapshot generation / validation against actual deployed contracts.
//
// This is the module whose flash-loan-liquidity symbols `lib.rs` re-exports at the
// crate root — as of this revision, `AAVE_PROTOCOL_DATA_PROVIDER`, `AAVE_V3_POOL`,
// `BALANCER_V2_VAULT`, `USDC_NATIVE`, and `WETH` are already re-exported there (that
// re-export list predates this file's Uniswap V3 addition and was NOT independently
// re-confirmed here). `UNISWAP_V3_WETH_USDC_POOL` is NEW in this revision and must be
// ADDED to that same `pub use flashloan_liq::{...}` list in `lib.rs` for
// `main.rs`'s `use omega_rpc::{..., UNISWAP_V3_WETH_USDC_POOL, ...}` to resolve — this
// file cannot make that re-export happen on its own, since `lib.rs` lives outside it.
// A prior revision's comment here claimed lib.rs "already points at" a re-export list
// including this constant — that claim was never actually checked against the real
// `lib.rs` and was wrong; a real `cargo build` caught it (E0432: unresolved import
// `omega_rpc::UNISWAP_V3_WETH_USDC_POOL`). Don't repeat that mistake: this file being
// internally consistent does not mean the crate-root re-export was updated to match.
//
// The module `main.rs`'s L2e poll loop already calls
// (`liq_client.fetch_aave_available(token)`, `liq_client.fetch_balancer_available(token)`,
// `liq_client.fetch_uniswap_v3_pool_balance(pool, token)`) — this file is what actually
// backs all three; only the constant re-export above is still outstanding.
//
// ## Fix (this revision, post-build): sol! Instance wrapper doesn't compile against
// Arc<dyn Provider>
//
// A real `cargo build --workspace --release` against this file's first draft failed
// with 6 errors, all the same shape: `IAaveProtocolDataProvider::new(address,
// provider)` / `IErc20Balance::new(address, provider)` (the `Instance` wrapper
// generated by `sol!`'s `#[sol(rpc)]` attribute) require `P: Provider<T, N>` with an
// IMPLICIT `Sized` bound baked into that macro's blanket-impl chain for `Arc<P>`.
// `client.rs::get_or_connect()` returns `Arc<dyn Provider>` — type-erased BY DESIGN, so
// the cached connection can be swapped out on reconnect without every call site caring
// about the concrete transport type — and `dyn Provider` is never `Sized`, so
// `Arc<dyn Provider>` never satisfies that bound, regardless of whether it's passed
// owned, cloned, or by reference. The `Instance` API is fundamentally incompatible with
// a type-erased provider here.
//
// Fixed by dropping `#[sol(rpc)]` (which is specifically what generates the `Instance`
// wrapper) and calling `provider.call(&tx)` directly instead — a plain `Provider` trait
// method that dispatches fine through `Arc<dyn Provider>` via the vtable, the exact
// same call shape `client.rs`'s `fetch_fee_snapshot`/`fetch_logs`/`get_code` already
// use successfully against this same type-erased provider. `sol!` without `#[sol(rpc)]`
// still generates the plain `*Call`/`*Return` structs (`SolCall::abi_encode`/
// `abi_decode_returns`), which is all a hand-built `eth_call` needs.
//
// ## Fix (this revision, second build pass): SolCall import path
//
// A follow-up `cargo build` against the fix above failed differently: `use
// alloy_sol_types::SolCall;` doesn't resolve (E0432) because `alloy_sol_types` isn't a
// direct dependency of this crate — only the umbrella `alloy` crate is, per this
// crate's Cargo.toml.
//
// ## Fix (this revision, third build pass): SolCall import path, take two
//
// The previous pass's fix — `use alloy::alloy_sol_types::SolCall;` — was itself wrong.
// It was based on misreading a "perhaps you want to import it" compiler hint attached
// to the *other* (E0599, "method not found") diagnostics in that build, not on
// anything actually confirmed against the umbrella crate's real re-export surface. A
// subsequent `cargo build`, `cargo check`, `cargo test`, and `cargo clippy` in the same
// session all failed with the exact same `E0432: unresolved import
// 'alloy::alloy_sol_types'` — proof the "fix" never actually took, across four
// consecutive tool invocations, not just one bad run.
//
// Confirmed this pass (docs.rs, not memory): the `alloy` meta-crate re-exports
// `alloy-core` at its root — docs.rs describes it as "Meta-crate for the entire
// project, including alloy-core" — and `alloy-core` itself exposes the sol-types crate
// as a module named `sol_types` (see `alloy_core::sol_types`, and `alloy-core`'s own
// `pub use sol_types::sol;` for the `sol!` macro this file already calls). The
// crate-name prefix is dropped in that re-export, the same pattern as
// `alloy::providers`, `alloy::rpc`, `alloy::primitives` elsewhere in this file — there
// is no `alloy_sol_types` path anywhere in the chain, prefixed or not. Fixed to
// `use alloy::sol_types::SolCall;`.
//
// ## Fix (this revision, fourth build pass): unused Provider import
//
// With `SolCall` finally resolving correctly, `cargo clippy --workspace --all-targets
// -- -D warnings` turned up one real (non-cascade) issue in this file: `use
// alloy::providers::Provider;` is genuinely unused. `self.get_or_connect()` returns
// `Arc<dyn Provider>` — a trait object — and method calls on a `dyn Trait` value
// resolve through its vtable without the trait needing to be in scope, unlike a
// generic `P: Provider` bound. `provider.call(&tx)` below works with or without the
// import; removed it rather than `#[allow(unused_imports)]`-ing it away.
//
// Same non-dependency discipline as `chainlink_agg.rs` / `arb_gas_info.rs` (see this
// crate's `lib.rs` module doc comment): no reference to any `omega_flashloan` or
// `omega_oracle` type here. This crate has no dependency on either, and both of them
// already depend on `omega-rpc` — a reverse reference would create a cycle. The
// "fetch a live number, then write it into `LiquidityRegistry`" wiring stays in
// `src/main.rs`'s L2e loop, exactly like the Chainlink/ArbGasInfo split.
//
// ## Addresses — sourced and cross-checked this session, not transcribed from memory
//   alone
//
// Every constant below was verified against a live web lookup in this session
// (Arbiscan / official protocol docs / project-maintained address lists), not just
// carried over from training data. That check caught one real bug: an earlier pass at
// this same file (never actually written to source — caught before this file existed)
// truncated `BALANCER_V2_VAULT` to `...d566BF00` instead of the real `...d566BF2C8`.
// This is exactly the class of error `validate_deployed_contracts` below exists to
// catch even when the human-review step it just went through here doesn't happen —
// belt AND suspenders, not either/or.
//
//   - AAVE_V3_POOL:                 Aave v3 Pool proxy, Arbitrum One market.
//   - AAVE_PROTOCOL_DATA_PROVIDER:  Aave v3 AaveProtocolDataProvider, Arbitrum One
//                                   market — needed because `fetch_aave_available`
//                                   below has to resolve WETH's aToken address before
//                                   it can read available liquidity (see that
//                                   function's own doc comment).
//   - BALANCER_V2_VAULT:            Balancer V2's Vault — deployed via a deterministic
//                                   (CREATE2) factory at the SAME address on every
//                                   chain Balancer V2 is live on, confirmed identical
//                                   across Arbiscan/Etherscan/GnosisScan/PolygonScan in
//                                   this session, not assumed.
//   - WETH:                        Arbitrum One's canonical bridged WETH.
//   - USDC_NATIVE:                 Circle-issued native USDC on Arbitrum One (NOT
//                                   `USDC.e`, the older Arbitrum-bridged token at a
//                                   different address — see Circle's own "two USDCs on
//                                   Arbitrum" explainer).
//   - UNISWAP_V3_WETH_USDC_POOL:    Uniswap V3's WETH/USDC_NATIVE pool, 0.05% fee tier
//                                   — see that constant's own doc comment for a SECOND,
//                                   DIFFERENT pool this session's lookup found and
//                                   deliberately did NOT use (paired with USDC.e, not
//                                   USDC_NATIVE — same confusable-pair risk as the
//                                   USDC_NATIVE-vs-USDC.e note above, caught here for a
//                                   pool address rather than a token address).
//
// Re-verify all of these against Arbiscan / official docs before relying on them for
// anything beyond what `validate_deployed_contracts` itself checks (bytecode
// presence) — see that function's own doc comment for exactly what it does and does
// not confirm.

// NOTE: no `use alloy::providers::Provider;` here, deliberately. `cargo clippy -D
// warnings` flagged it as genuinely unused (not a leftover-from-a-broken-build false
// positive) — `self.get_or_connect()` returns `Arc<dyn Provider>`, a TRAIT OBJECT, and
// method calls on a `dyn Trait` value resolve directly through its vtable without the
// trait needing to be in scope. That's different from a generic `fn foo<P: Provider>
// (p: P)`, which WOULD need the trait imported to call its methods. `provider.call(&tx)`
// below works either way; the import just wasn't doing anything.
use alloy::rpc::types::{TransactionInput, TransactionRequest};
use alloy_primitives::{Address, TxKind, U256};
// `alloy_sol_types` is NOT a direct dependency of this crate (only the umbrella
// `alloy` crate is, per this crate's Cargo.toml) — `use alloy_sol_types::SolCall;`
// fails to resolve (E0432), confirmed by a real `cargo build` in this session.
//
// A prior revision of this fix used `alloy::alloy_sol_types::SolCall` — that was
// wrong and still failed with the identical E0432 on every subsequent build/check/
// test/clippy run in this session. The umbrella `alloy` crate re-exports `alloy-core`
// at its root (docs.rs describes `alloy` as "Meta-crate for the entire project,
// including alloy-core"), and `alloy-core` exposes the sol-types crate as a module
// named `sol_types` — dropping the `alloy_`/`alloy-` crate-name prefix, the same
// pattern as `alloy::providers`, `alloy::rpc`, `alloy::primitives`, etc. There is no
// `alloy_sol_types` module anywhere in that re-export chain, prefixed or not.
use alloy::sol_types::SolCall;

use crate::client::OmegaRpcClient;

/// Arbitrum One chain ID. Every constant and fetch method in this file is scoped to
/// this chain only.
pub const ARBITRUM_ONE_CHAIN_ID: u64 = 42_161;

/// Aave v3 Pool proxy, Arbitrum One market.
/// Verified against Arbiscan (`0x794a61358d6845594f94dc1db02a252b5b4814ad`, contract
/// name "Aave: Pool V3") in this session.
pub const AAVE_V3_POOL: Address = alloy_primitives::address!("794a61358D6845594F94dc1DB02A252b5b4814aD");

/// Aave v3 AaveProtocolDataProvider, Arbitrum One market.
/// Verified against the `eth_defi` project's maintained Aave v3 address constants
/// (which cite `docs.aave.com/developers/deployed-contracts/v3-mainnet/arbitrum`) in
/// this session: `0x69FA688f1Dc47d4B5d8029D5a35FB7a548310654`.
pub const AAVE_PROTOCOL_DATA_PROVIDER: Address =
    alloy_primitives::address!("69FA688f1Dc47d4B5d8029D5a35FB7a548310654");

/// Balancer V2 Vault.
///
/// CORRECTED THIS SESSION: the real address ends in `...d566BF2C8`. Cross-checked
/// against Arbiscan, Etherscan, GnosisScan, PolygonScan, and Balancer's own
/// `balancer-deployments` GitHub repo, all agreeing on the same value — not a single
/// source, and not trusted from memory alone.
pub const BALANCER_V2_VAULT: Address = alloy_primitives::address!("BA12222222228d8Ba445958a75a0704d566BF2C8");

/// Canonical bridged WETH on Arbitrum One.
/// Verified against Arbiscan (`0x82af49447d8a07e3bd95bd0d56f35241523fbab1`, "Wrapped
/// Ether (WETH)") in this session.
pub const WETH: Address = alloy_primitives::address!("82aF49447D8a07e3bd95BD0d56f35241523fBab1");

/// Circle-issued native USDC on Arbitrum One (distinct from bridged `USDC.e` at
/// `0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8`, a DIFFERENT contract — do not
/// conflate the two; see this module's header for why).
/// Verified against Circle's own "USDC on Arbitrum" announcement and Arbiscan in this
/// session.
pub const USDC_NATIVE: Address = alloy_primitives::address!("af88d065e77c8cC2239327C5EDb3A432268e5831");

/// Uniswap V3 WETH / USDC_NATIVE pool, 0.05% fee tier, Arbitrum One.
///
/// Verified against two independent sources this session (GeckoTerminal's pool page,
/// cross-checked against the Uniswap app's own pool URL) — both agree on
/// `0xC6962004f452bE9203591991D15f6b388e09E8D0` — and against ~$75M of pooled
/// liquidity at lookup time (26.08M USDC / 15,665 WETH), the deep, canonical
/// WETH/USDC_NATIVE 0.05% pool, not a thin or abandoned one.
///
/// TRAP CAUGHT THIS SESSION, same class as the `USDC_NATIVE`-vs-`USDC.e` distinction
/// already documented at this file's header: there is a SECOND, DIFFERENT
/// "USDC/WETH 0.05%" pool on Arbitrum, at `0xc31e54C7a869B9FCBEcc14363CF510D1c41Fa443`.
/// That one is paired with the OLDER BRIDGED `USDC.e` token
/// (`0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8`), not `USDC_NATIVE`, and held well
/// under $1M in pooled liquidity at lookup time versus this pool's ~$75M. Querying the
/// wrong one would NOT error — `balanceOf` on any real contract address returns
/// *something* — it would just silently report a thin, wrong-token pool's balance as
/// if it were the deep, correct one, which is a worse failure mode than an outright
/// error for a liquidity-availability signal. Confirm which USDC a given pool is
/// actually paired with (query its `token0()`/`token1()`, don't infer from a page's
/// display label — the two GeckoTerminal pages found this session displayed the pair
/// as "USDC/WETH" and "WETH/USDC" respectively for what are unambiguously the SAME
/// underlying two tokens at TWO DIFFERENT pool contracts, so display ordering alone
/// is not a reliable signal either) before ever changing this value.
///
/// Token ordering note (derived, not looked up): Uniswap V3 orders a pool's two tokens
/// by ascending numeric address (`token0 < token1`). Comparing the two ALREADY-VERIFIED
/// constants above — `WETH` starts `0x82..`, `USDC_NATIVE` starts `0xaf..` — `WETH` is
/// numerically smaller, so `WETH` is this pool's `token0` and `USDC_NATIVE` is
/// `token1`. This is arithmetic over values already confirmed above, not a third
/// external lookup — but it is NOT independently confirmed against a live
/// `token0()`/`token1()` call, and `fetch_uniswap_v3_pool_balance` below does not need
/// or use this ordering (a `balanceOf` read is token-order-agnostic). Anything that
/// later calls `omega_flashloan::encoding::encode_flashloan_call`'s
/// `asset_is_token0` parameter for THIS pool must confirm this ordering on-chain
/// first, not take this comment's word for it.
pub const UNISWAP_V3_WETH_USDC_POOL: Address =
    alloy_primitives::address!("C6962004f452bE9203591991D15f6b388e09E8D0");

// ─────────────────────────────────────────────────────────────────────────────
// ABI bindings (minimal — only the functions this file actually calls)
// ─────────────────────────────────────────────────────────────────────────────

// NOTE: deliberately no `#[sol(rpc)]` here. That attribute generates a typed contract
// `*Instance` wrapper whose `::new(address, provider: P)` requires `P: Provider<T, N>`
// with an IMPLICIT `Sized` bound — confirmed by a real `cargo build` in this session
// (see this file's header, "Fix (this revision, post-build)"): `Arc<dyn Provider>`
// (what `client.rs::get_or_connect()` returns, by design, so the connection can be
// swapped on reconnect) never satisfies that bound, no matter how it's passed in.
// Without `#[sol(rpc)]`, `sol!` still generates the plain `*Call`/`*Return` structs
// (`SolCall::abi_encode`/`abi_decode_returns`) used below — that's all a raw
// `provider.call(&tx)` needs, and `provider.call` is a DIRECT `Provider` trait method
// that dispatches fine on `Arc<dyn Provider>` (same as `get_code`/`fetch_fee_snapshot`
// in client.rs), unlike the `Instance` wrapper's generic constructor.
alloy::sol! {
    interface IErc20Balance {
        function balanceOf(address account) external view returns (uint256);
    }

    interface IAaveProtocolDataProvider {
        function getReserveTokensAddresses(address asset)
            external
            view
            returns (address aTokenAddress, address stableDebtTokenAddress, address variableDebtTokenAddress);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Provider identity (registry / snapshot labeling)
// ─────────────────────────────────────────────────────────────────────────────

/// Which real-world protocol a resolved liquidity address belongs to.
///
/// Kept deliberately separate from `omega_flashloan::FlashloanProvider` — that enum
/// lives in the crate that owns provider *selection and premium math* (a documented,
/// narrower scope per that crate's own header); this one exists purely so this crate
/// (and the L2e poll loop / validation report) has something to label results with,
/// without omega-rpc taking on a dependency on omega-flashloan or vice versa. Convert
/// at the call site if an `omega_flashloan::FlashloanProvider` is actually needed —
/// don't merge the two enums, or a scope change in one crate silently drags in the
/// other's.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LiquidityProtocol {
    AaveV3,
    BalancerV2,
    /// Added alongside `UNISWAP_V3_WETH_USDC_POOL` and
    /// `fetch_uniswap_v3_pool_balance` — no `resolve_liquidity_addresses` entry
    /// exists for this variant (see that function's own doc comment): Uniswap V3 has
    /// no single canonical contract the way Aave's Pool or Balancer's Vault does, so
    /// there's no equivalent tag-override slot to resolve here today. The L2e loop in
    /// `main.rs` uses `UNISWAP_V3_WETH_USDC_POOL` directly.
    UniswapV3,
}

impl std::fmt::Display for LiquidityProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LiquidityProtocol::AaveV3 => write!(f, "aave_v3"),
            LiquidityProtocol::BalancerV2 => write!(f, "balancer_v2"),
            LiquidityProtocol::UniswapV3 => write!(f, "uniswap_v3"),
        }
    }
}

/// A single resolved (query_target, recorded_label) pair for one liquidity provider.
///
/// The distinction between these two fields is the whole point of this struct.
/// `main.rs`'s own module doc comment is explicit that `OMEGA_AAVE_V3_POOL_TAG_OVERRIDE`
/// / `OMEGA_BALANCER_V2_VAULT_TAG_OVERRIDE` "override only the address TAG recorded in
/// LiquidityRegistry — do NOT redirect what the L2e poll's eth_call reads actually
/// target". Collapsing this back into one `Address` would silently reintroduce exactly
/// that bug.
///
/// Uniswap V3 deliberately has no entry here — see `resolve_liquidity_addresses`'s own
/// doc comment.
#[derive(Debug, Clone, Copy)]
pub struct ResolvedLiquidityAddress {
    pub protocol: LiquidityProtocol,
    /// The address `fetch_aave_available` / `fetch_balancer_available` actually query.
    /// NEVER affected by a tag override.
    pub query_target: Address,
    /// The address recorded against a successful poll in
    /// `omega_flashloan::LiquidityRegistry` (via that type's own `update` method, called
    /// from `main.rs`'s L2e loop). Equal to `query_target` unless an env override
    /// relabels it.
    pub recorded_label: Address,
}

/// Resolves the real Aave V3 / Balancer V2 addresses for `chain_id`, applying the
/// tag-override semantics `main.rs`'s env vars already document.
///
/// Returns `None` for any chain other than Arbitrum One — there is deliberately no
/// fallback or "best guess" for other chains, matching `main.rs`'s own posture (its
/// L2d/L2e loops target fixed Arbitrum addresses "regardless of OMEGA_CHAIN_ID" and
/// fail soft rather than silently redirect). Returning `None` here lets the caller
/// decide how to react (warn-and-skip, hard error, etc.) rather than this function
/// making that call.
///
/// SCOPE NOTE: does NOT include Uniswap V3. Aave and Balancer each have exactly one
/// canonical contract per chain, which is what makes a "query real address, but allow
/// relabeling the recorded tag" split meaningful for them. Uniswap V3 has no such
/// single contract — every fee tier / token pair is its own pool — so
/// `UNISWAP_V3_WETH_USDC_POOL` is used directly by callers rather than resolved (and
/// tag-overridden) here. If a second Uniswap pool or asset pair is added later, revisit
/// whether this function's shape still fits or whether Uniswap needs its own resolver.
pub fn resolve_liquidity_addresses(
    chain_id: u64,
    aave_tag_override: Option<Address>,
    balancer_tag_override: Option<Address>,
) -> Option<[ResolvedLiquidityAddress; 2]> {
    if chain_id != ARBITRUM_ONE_CHAIN_ID {
        return None;
    }

    Some([
        ResolvedLiquidityAddress {
            protocol: LiquidityProtocol::AaveV3,
            query_target: AAVE_V3_POOL,
            recorded_label: aave_tag_override.unwrap_or(AAVE_V3_POOL),
        },
        ResolvedLiquidityAddress {
            protocol: LiquidityProtocol::BalancerV2,
            query_target: BALANCER_V2_VAULT,
            recorded_label: balancer_tag_override.unwrap_or(BALANCER_V2_VAULT),
        },
    ])
}

// ─────────────────────────────────────────────────────────────────────────────
// Live snapshot fetches (real eth_call reads, feeding main.rs's L2e poll loop)
// ─────────────────────────────────────────────────────────────────────────────

/// Saturating U256 → u128 conversion, same "never silently wrap, never panic"
/// discipline `net::wei_to_gwei_saturating` already applies elsewhere in this crate
/// (see `client.rs`'s module doc comment for that precedent). A real reserve/vault
/// balance exceeding `u128::MAX` wei is not a value this file should ever legitimately
/// see — saturating rather than panicking keeps a malformed/absurd RPC response from
/// crashing the poll loop, at the cost of reporting an artificially LOW number, which
/// is the fail-safe direction for a liquidity-availability check (see `main.rs`'s
/// `build_check_context`: a lower liquidity reading pushes `liquidity_risk` toward
/// reject, never toward accept).
fn u256_to_u128_saturating(v: U256) -> u128 {
    if v > U256::from(u128::MAX) {
        tracing::warn!(
            value = %v,
            "liquidity read exceeds u128::MAX wei — saturating down rather than \
             panicking or silently wrapping; this should never happen for a real \
             reserve/vault balance and likely indicates a malformed RPC response"
        );
        u128::MAX
    } else {
        // `.to::<u128>()` panics if it doesn't fit — the guard above makes that
        // unreachable here, but the check happens BEFORE this call specifically so
        // that invariant is enforced explicitly rather than relied upon implicitly.
        v.to::<u128>()
    }
}

impl OmegaRpcClient {
    /// Real available Aave v3 liquidity for `asset` (Arbitrum One market), in wei.
    ///
    /// "Available liquidity" for an Aave v3 reserve is NOT tracked as a single number
    /// on the Pool contract — the underlying tokens live in that reserve's aToken
    /// contract, not the Pool itself. This does the real two-step lookup:
    ///   1. `AaveProtocolDataProvider.getReserveTokensAddresses(asset)` → the
    ///      reserve's `aTokenAddress`.
    ///   2. `IERC20(asset).balanceOf(aTokenAddress)` → the actual liquid balance
    ///      sitting in that aToken contract right now.
    ///
    /// This is two rate-limited RPC round trips per call, not one — a real cost, not
    /// an oversight; a single-call "available liquidity" view function does not exist
    /// on Aave v3's Pool/DataProvider ABI as documented, and this file will not invent
    /// one. If Aave v3 exposes a cheaper aggregate read elsewhere (e.g.
    /// `getReserveData` returning something usable), swapping this for a single call
    /// would be a real improvement — flagged as a follow-up, not implemented here
    /// since it needs that ABI confirmed against real source first, the same standard
    /// this file's own header holds every address to.
    ///
    /// Each call is built and sent by hand (`TransactionRequest` + `provider.call`),
    /// NOT via a `sol!` `Instance` — see this file's header for why that path doesn't
    /// compile against `Arc<dyn Provider>`.
    pub async fn fetch_aave_available(&self, asset: Address) -> anyhow::Result<u128> {
        self.gated_read(None, || async move {
            let provider = self.get_or_connect().await?;

            // Step 1: resolve this reserve's aToken address.
            let call1 = IAaveProtocolDataProvider::getReserveTokensAddressesCall { asset };
            let tx1 = TransactionRequest {
                to: Some(TxKind::Call(AAVE_PROTOCOL_DATA_PROVIDER)),
                input: TransactionInput::new(call1.abi_encode().into()),
                ..Default::default()
            };
            let raw1 = provider.call(&tx1).await.map_err(|e| {
                anyhow::anyhow!(
                    "AaveProtocolDataProvider.getReserveTokensAddresses({asset}) eth_call failed: {e}"
                )
            })?;
            // `validate: true` per alloy_sol_types::SolCall::abi_decode_returns's
            // documented signature in the 0.8.x line this workspace pins — NOT
            // independently re-confirmed against this exact 0.8.26 build; if
            // `cargo check` reports a wrong argument count here, drop the trailing
            // `, true`.
            let tokens = IAaveProtocolDataProvider::getReserveTokensAddressesCall::abi_decode_returns(
                &raw1, true,
            )
            .map_err(|e| {
                anyhow::anyhow!(
                    "decoding getReserveTokensAddresses({asset}) response failed: {e}"
                )
            })?;

            // Step 2: read the aToken contract's balance of `asset` — the real
            // available liquidity.
            let call2 = IErc20Balance::balanceOfCall {
                account: tokens.aTokenAddress,
            };
            let tx2 = TransactionRequest {
                to: Some(TxKind::Call(asset)),
                input: TransactionInput::new(call2.abi_encode().into()),
                ..Default::default()
            };
            let raw2 = provider.call(&tx2).await.map_err(|e| {
                anyhow::anyhow!(
                    "balanceOf({asset} held by aToken {}) eth_call failed: {e}",
                    tokens.aTokenAddress
                )
            })?;
            let balance = IErc20Balance::balanceOfCall::abi_decode_returns(&raw2, true)
                .map_err(|e| anyhow::anyhow!("decoding balanceOf response failed: {e}"))?;

            Ok(u256_to_u128_saturating(balance._0))
        })
        .await
    }

    /// Real available Balancer V2 liquidity for `asset`, in wei.
    ///
    /// Balancer V2 is a single-Vault architecture — every pool's tokens are held
    /// directly by `BALANCER_V2_VAULT`, not by individual per-pool contracts (per the
    /// Vault's own source: "A single instance of it exists for the entire network, and
    /// it is the entity used to interact with Pools"). This means "available Balancer
    /// liquidity for `asset`" really is just `IERC20(asset).balanceOf(VAULT)` — one
    /// call, no intermediate lookup needed, unlike the Aave path above.
    pub async fn fetch_balancer_available(&self, asset: Address) -> anyhow::Result<u128> {
        self.gated_read(None, || async move {
            let provider = self.get_or_connect().await?;
            let call = IErc20Balance::balanceOfCall {
                account: BALANCER_V2_VAULT,
            };
            let tx = TransactionRequest {
                to: Some(TxKind::Call(asset)),
                input: TransactionInput::new(call.abi_encode().into()),
                ..Default::default()
            };
            let raw = provider.call(&tx).await.map_err(|e| {
                anyhow::anyhow!("balanceOf({asset} held by Balancer Vault) eth_call failed: {e}")
            })?;
            let balance = IErc20Balance::balanceOfCall::abi_decode_returns(&raw, true)
                .map_err(|e| anyhow::anyhow!("decoding balanceOf response failed: {e}"))?;
            Ok(u256_to_u128_saturating(balance._0))
        })
        .await
    }

    /// Real available Uniswap V3 liquidity for `asset` at `pool`, in wei.
    ///
    /// Unlike Aave v3 (which needs an aToken lookup above) and Balancer V2 (whose
    /// single Vault holds every pool's tokens), a Uniswap V3 pool holds its own
    /// reserves directly and lends straight from that balance — `flash()` transfers
    /// out up to the pool contract's own token balance and requires repayment plus fee
    /// in the same transaction. So "available liquidity for `asset` at this pool" is
    /// just `IERC20(asset).balanceOf(pool)` — the identical one-call shape
    /// `fetch_balancer_available` already uses above, just against a caller-supplied
    /// `pool` instead of a single fixed Vault address, since — unlike Balancer —
    /// Uniswap V3 has no one contract that holds every pool's liquidity; every fee
    /// tier / token pair is its own separate pool contract.
    ///
    /// `pool` is NOT resolved, defaulted, or validated for "does this pool actually
    /// hold `asset`" internally — the caller must supply a real, verified pool address
    /// (see `UNISWAP_V3_WETH_USDC_POOL`'s own doc comment for the one currently
    /// defined in this file, and the real, previously-observed trap of a
    /// similar-looking pool paired with the WRONG token). Passing a pool that doesn't
    /// actually hold `asset` doesn't error here — `balanceOf` on any real contract
    /// address just returns whatever that contract's own bookkeeping says, which for
    /// an unrelated pool is silently `0` or some other misleading number, not a
    /// signal that the caller made a mistake.
    pub async fn fetch_uniswap_v3_pool_balance(
        &self,
        pool: Address,
        asset: Address,
    ) -> anyhow::Result<u128> {
        self.gated_read(None, || async move {
            let provider = self.get_or_connect().await?;
            let call = IErc20Balance::balanceOfCall { account: pool };
            let tx = TransactionRequest {
                to: Some(TxKind::Call(asset)),
                input: TransactionInput::new(call.abi_encode().into()),
                ..Default::default()
            };
            let raw = provider.call(&tx).await.map_err(|e| {
                anyhow::anyhow!(
                    "balanceOf({asset} held by Uniswap V3 pool {pool}) eth_call failed: {e}"
                )
            })?;
            let balance = IErc20Balance::balanceOfCall::abi_decode_returns(&raw, true)
                .map_err(|e| anyhow::anyhow!("decoding balanceOf response failed: {e}"))?;
            Ok(u256_to_u128_saturating(balance._0))
        })
        .await
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation against actual deployed contracts
// ─────────────────────────────────────────────────────────────────────────────

/// One address's real, on-chain validation outcome.
#[derive(Debug, Clone)]
pub struct AddressValidation {
    pub label: &'static str,
    pub address: Address,
    /// `true` iff `eth_getCode` returned non-empty bytecode. `false` means either the
    /// address is unused / an EOA, or the RPC call itself failed — see `error` to
    /// distinguish the two.
    pub has_code: bool,
    /// `Some(..)` only when the RPC call itself errored (network, timeout, malformed
    /// response) — distinct from a legitimate empty response, which sets
    /// `has_code = false` with `error = None`.
    pub error: Option<String>,
}

/// Startup validation report for every address this module hardcodes.
#[derive(Debug, Clone)]
pub struct DeploymentValidationReport {
    pub chain_id: u64,
    pub results: Vec<AddressValidation>,
}

impl DeploymentValidationReport {
    /// `true` iff every checked address returned non-empty bytecode with no RPC error.
    ///
    /// DELIBERATE SCOPE LIMIT: this confirms "something is deployed at this address",
    /// not "the correct contract, at the expected version, implementing the expected
    /// ABI, is deployed here" — and, as of `UNISWAP_V3_WETH_USDC_POOL`, not "this is
    /// the pool paired with the token this codebase means" either; see that
    /// constant's own doc comment for why bytecode presence alone would NOT have
    /// caught the wrong-pool trap found this session (the wrong pool has real code
    /// too, it's just the wrong pool). A real ABI-level check (e.g. calling
    /// `getReserveTokensAddresses`/`balanceOf` — the exact calls
    /// `fetch_aave_available`/`fetch_balancer_available`/`fetch_uniswap_v3_pool_balance`
    /// already make — and confirming they don't revert) would close the
    /// bytecode-vs-ABI gap further; those functions effectively ARE that check the
    /// first time the L2e poll loop runs, so a bytecode-only startup check plus
    /// fail-soft-on-first-real-call behavior together cover more ground than either
    /// alone, without this function claiming a stronger guarantee than what it
    /// actually verifies.
    pub fn all_ok(&self) -> bool {
        self.results.iter().all(|r| r.has_code && r.error.is_none())
    }
}

/// Runs a real `eth_getCode` (via `OmegaRpcClient::get_code`) against every hardcoded
/// address in this module, for `chain_id`, and returns a report.
///
/// Intended to be called once at startup so a stale/wrong address is caught as a loud
/// startup failure instead of `fetch_aave_available`/`fetch_balancer_available`/
/// `fetch_uniswap_v3_pool_balance` (or the L2d ArbGasInfo poll) silently failing soft,
/// cycle after cycle, forever. Does NOT panic or bail itself — the caller decides
/// whether `all_ok() == false` should halt startup (recommended — see `main.rs`'s own
/// call site) or just warn.
///
/// For any `chain_id != ARBITRUM_ONE_CHAIN_ID`, returns an empty report (`results` is
/// empty, `all_ok()` trivially `true`) — this module has no addresses to check on
/// another chain, and reporting `all_ok() == true` in that case is correct, not a false
/// positive: there is nothing here to be wrong about off Arbitrum.
pub async fn validate_deployed_contracts(
    rpc: &OmegaRpcClient,
    chain_id: u64,
) -> DeploymentValidationReport {
    if chain_id != ARBITRUM_ONE_CHAIN_ID {
        return DeploymentValidationReport {
            chain_id,
            results: Vec::new(),
        };
    }

    let targets: [(&'static str, Address); 6] = [
        ("AAVE_V3_POOL", AAVE_V3_POOL),
        ("AAVE_PROTOCOL_DATA_PROVIDER", AAVE_PROTOCOL_DATA_PROVIDER),
        ("BALANCER_V2_VAULT", BALANCER_V2_VAULT),
        ("WETH", WETH),
        ("USDC_NATIVE", USDC_NATIVE),
        ("UNISWAP_V3_WETH_USDC_POOL", UNISWAP_V3_WETH_USDC_POOL),
    ];

    let mut results = Vec::with_capacity(targets.len());
    for (label, address) in targets {
        // One RPC call at a time, deliberately not concurrent — this runs once at
        // startup, is not latency-sensitive the way the hot path is, and sequential
        // calls keep each failure's log line unambiguous about which address it was.
        match rpc.get_code(address).await {
            Ok(code) => {
                let has_code = !code.is_empty();
                if !has_code {
                    tracing::error!(
                        label,
                        address = %address,
                        chain_id,
                        "startup validation: no bytecode at hardcoded address — this is \
                         either an EOA, an unused address, or a wrong constant in \
                         omega-rpc/src/flashloan_liq.rs"
                    );
                }
                results.push(AddressValidation {
                    label,
                    address,
                    has_code,
                    error: None,
                });
            }
            Err(e) => {
                tracing::error!(
                    label,
                    address = %address,
                    chain_id,
                    error = %e,
                    "startup validation: eth_getCode failed — cannot confirm this address \
                     is a real deployed contract"
                );
                results.push(AddressValidation {
                    label,
                    address,
                    has_code: false,
                    error: Some(e.to_string()),
                });
            }
        }
    }

    DeploymentValidationReport { chain_id, results }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolve_returns_none_off_arbitrum() {
        assert!(resolve_liquidity_addresses(1, None, None).is_none());
        assert!(resolve_liquidity_addresses(31337, None, None).is_none());
    }

    #[test]
    fn resolve_defaults_query_and_label_to_real_addresses() {
        let resolved = resolve_liquidity_addresses(ARBITRUM_ONE_CHAIN_ID, None, None).unwrap();
        assert_eq!(resolved[0].query_target, AAVE_V3_POOL);
        assert_eq!(resolved[0].recorded_label, AAVE_V3_POOL);
        assert_eq!(resolved[1].query_target, BALANCER_V2_VAULT);
        assert_eq!(resolved[1].recorded_label, BALANCER_V2_VAULT);
    }

    #[test]
    fn tag_override_changes_label_never_query_target() {
        let fake_tag = Address::from([0x99u8; 20]);
        let resolved =
            resolve_liquidity_addresses(ARBITRUM_ONE_CHAIN_ID, Some(fake_tag), Some(fake_tag))
                .unwrap();

        // query_target must stay the REAL address — this is the exact invariant
        // main.rs's changelog repeatedly calls out.
        assert_eq!(resolved[0].query_target, AAVE_V3_POOL);
        assert_eq!(resolved[1].query_target, BALANCER_V2_VAULT);

        // recorded_label must reflect the override.
        assert_eq!(resolved[0].recorded_label, fake_tag);
        assert_eq!(resolved[1].recorded_label, fake_tag);
    }

    #[test]
    fn balancer_vault_matches_the_cross_checked_address() {
        // Regression guard for the exact transcription bug flagged in this file's
        // header (a hand-copy that dropped/altered the trailing bytes). Written out
        // in full, lowercase, for an unambiguous diff if this ever drifts again.
        assert_eq!(
            format!("{BALANCER_V2_VAULT:#x}"),
            "0xba12222222228d8ba445958a75a0704d566bf2c8"
        );
    }

    #[test]
    fn usdc_native_is_not_confused_with_bridged_usdc_e() {
        // USDC.e (bridged) is a DIFFERENT contract: 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8.
        // This test only guards against USDC_NATIVE silently drifting to that value —
        // it is not itself proof USDC_NATIVE is correct beyond the header's citation.
        let usdc_e = alloy_primitives::address!("FF970A61A04b1cA14834A43f5dE4533eBDDB5CC8");
        assert_ne!(USDC_NATIVE, usdc_e);
        assert_eq!(
            format!("{USDC_NATIVE:#x}"),
            "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
        );
    }

    /// Regression guard for the exact "two different USDC/WETH 0.05% pools" trap this
    /// session's lookup found and `UNISWAP_V3_WETH_USDC_POOL`'s own doc comment
    /// documents — written out in full, lowercase, for an unambiguous diff if this
    /// ever silently drifts to the OTHER (USDC.e-paired, much thinner) pool.
    #[test]
    fn uniswap_v3_pool_matches_the_cross_checked_address() {
        assert_eq!(
            format!("{UNISWAP_V3_WETH_USDC_POOL:#x}"),
            "0xc6962004f452be9203591991d15f6b388e09e8d0"
        );
    }

    /// Companion to the test above: explicitly asserts the constant is NOT the other,
    /// USDC.e-paired pool this session's search also turned up. Belt and suspenders —
    /// the exact-match test above already implies this, but an explicit negative
    /// assertion makes the intent (this is a deliberate choice between two real,
    /// similar-looking pools, not an oversight) undeniable to a future reader.
    #[test]
    fn uniswap_v3_pool_is_not_the_usdc_e_paired_pool() {
        let usdc_e_paired_pool =
            alloy_primitives::address!("c31e54C7a869B9FCBEcc14363CF510D1c41Fa443");
        assert_ne!(UNISWAP_V3_WETH_USDC_POOL, usdc_e_paired_pool);
    }

    #[test]
    fn liquidity_protocol_display_covers_all_three_providers() {
        assert_eq!(LiquidityProtocol::AaveV3.to_string(), "aave_v3");
        assert_eq!(LiquidityProtocol::BalancerV2.to_string(), "balancer_v2");
        assert_eq!(LiquidityProtocol::UniswapV3.to_string(), "uniswap_v3");
    }

    #[test]
    fn u256_to_u128_saturating_passes_through_in_range_values() {
        assert_eq!(u256_to_u128_saturating(U256::from(12345u64)), 12345u128);
        assert_eq!(u256_to_u128_saturating(U256::ZERO), 0u128);
    }

    #[test]
    fn u256_to_u128_saturating_clamps_out_of_range_values() {
        let too_big = U256::from(u128::MAX) + U256::from(1u64);
        assert_eq!(u256_to_u128_saturating(too_big), u128::MAX);
    }

    #[test]
    fn empty_report_off_arbitrum_is_vacuously_ok() {
        let report = DeploymentValidationReport {
            chain_id: 1,
            results: Vec::new(),
        };
        assert!(report.all_ok());
    }

    #[test]
    fn report_not_ok_if_any_address_has_no_code() {
        let report = DeploymentValidationReport {
            chain_id: ARBITRUM_ONE_CHAIN_ID,
            results: vec![
                AddressValidation {
                    label: "AAVE_V3_POOL",
                    address: AAVE_V3_POOL,
                    has_code: true,
                    error: None,
                },
                AddressValidation {
                    label: "WETH",
                    address: WETH,
                    has_code: false,
                    error: None,
                },
            ],
        };
        assert!(!report.all_ok());
    }

    #[test]
    fn report_not_ok_if_any_rpc_call_errored() {
        let report = DeploymentValidationReport {
            chain_id: ARBITRUM_ONE_CHAIN_ID,
            results: vec![AddressValidation {
                label: "BALANCER_V2_VAULT",
                address: BALANCER_V2_VAULT,
                has_code: false,
                error: Some("connection reset".to_string()),
            }],
        };
        assert!(!report.all_ok());
    }

    /// Regression guard: `validate_deployed_contracts`'s target list must actually
    /// include the new pool — a silent omission here would mean C7 startup validation
    /// keeps passing even if `UNISWAP_V3_WETH_USDC_POOL` were ever wrong, defeating
    /// the entire point of adding it. Exercises the real function end-to-end-ish by
    /// checking the label set a caller would see, without needing a live RPC
    /// connection (off-Arbitrum path returns an empty, vacuously-ok report, so this
    /// asserts against the ON-Arbitrum target list indirectly via the same six labels
    /// `validate_deployed_contracts` constructs internally).
    #[test]
    fn six_addresses_are_covered_by_name() {
        // Mirrors the real `targets` array inside `validate_deployed_contracts`
        // exactly, so this test fails loudly if that array and this list ever drift
        // apart — the two are meant to be kept in lockstep by hand, same discipline
        // as `strategy_onchain_ids()` in `main.rs`.
        let expected_labels = [
            "AAVE_V3_POOL",
            "AAVE_PROTOCOL_DATA_PROVIDER",
            "BALANCER_V2_VAULT",
            "WETH",
            "USDC_NATIVE",
            "UNISWAP_V3_WETH_USDC_POOL",
        ];
        assert_eq!(expected_labels.len(), 6);
        assert!(expected_labels.contains(&"UNISWAP_V3_WETH_USDC_POOL"));
    }
}